# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mailer.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=128)),
                ('receivers', mailer.utils.models.EmailListField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=128, null=True)),
                ('cc', mailer.utils.models.EmailListField(blank=True, max_length=128, null=True)),
                ('message', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('response', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='emailstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.Status'),
        ),
    ]
