# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='to',
            new_name='recipients',
        ),
        migrations.RemoveField(
            model_name='email',
            name='bcc',
        ),
    ]
